### ISSUE TITLE
[1.15.2 ] Crash with latest refined storage mod

### ISSUE THREAD

**Issue by realTIMematrix** [TheLMiffy1111/RSLargePatterns#1]
Hi,

the mod does not work with the new version of refined storage:

Forge: forge-31.2.20
refinedstorage-1.8.5.jar
RSLargePatterns-1.15.2-2.0.0.0.jar

[Crash Log](https://pastebin.com/ehRGYnLn)

[Latest.log](https://pastebin.com/i2YNWbJu)

**Comment by TheLMiffy1111** [comment]
Updated
